mail.smtp.host=smtp.gmail.com
mail.smtp.port=465
mail.smtp.username=VOTRE_EMAIL@gmail.com
mail.smtp.password=VOTRE_APP_PASSWORD_GMAIL
mail.smtp.auth=true

mail.from.address=VOTRE_EMAIL@gmail.com
mail.from.name=ForestGuard

mail.alert.recipients=VOTRE_EMAIL@gmail.com

mail.smtp.connectiontimeout=10000
mail.smtp.timeout=10000
mail.smtp.writetimeout=10000
mail.smtp.ssl.trust=smtp.gmail.com
